### ISSUE TITLE
The issue with the dataset during the training process.

### ISSUE THREAD

**Issue by jixiaofeng123** [facebookresearch/ov-seg#24]
Hello, when I run the Python script datasets/prepare_coco_stuff_sem_seg.py to generate a dataset, it shows 0it [00:00, ?it/s], and when I execute python train_net.py --num-gpu 1 --config-file configs/ovseg_swinB_vitL_bs32_120k.yaml MODEL.CLIP_ADAPTER.MASK_PROMPT_FWD False, I encounter the following error.
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
relative_position_bias_table
Traceback (most recent call last):
  File "train_net.py", line 302, in <module>
    launch(
  File "/usr/local/lib/python3.8/dist-packages/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "train_net.py", line 294, in main
    trainer = Trainer(cfg)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/engine/defaults.py", line 378, in __init__
    data_loader = self.build_train_loader(cfg)
  File "train_net.py", line 106, in build_train_loader
    return build_detection_train_loader(cfg, mapper=mapper, dataset=dataset)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/root/ov-seg/open_vocab_seg/data/build.py", line 164, in _train_loader_from_config
    dataset = get_detection_dataset_dicts(
  File "/root/ov-seg/open_vocab_seg/data/build.py", line 127, in get_detection_dataset_dicts
    dataset_dicts = [
  File "/root/ov-seg/open_vocab_seg/data/build.py", line 128, in <listcomp>
    wrap_metas(DatasetCatalog.get(dataset_name), dataset_name=dataset_name)
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/catalog.py", line 58, in get
    return f()
  File "/root/ov-seg/open_vocab_seg/data/datasets/register_coco_stuff.py", line 235, in <lambda>
    lambda x=image_dir, y=gt_dir: load_sem_seg(
  File "/usr/local/lib/python3.8/dist-packages/detectron2/data/datasets/coco.py", line 274, in load_sem_seg
    assert len(gt_files) > 0, "No annotations found in {}.".format(gt_root)
AssertionError: No annotations found in datasets/coco/stuffthingmaps_detectron2/train2017.

**Comment by Jeff-LiangF** [comment]
Hi @jixiaofeng123 ,

Looks like there was some error with the data preparation. Could you double-check the data structure?
